// <auto-generated />
using EventApp.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EventApp.Persistence.Migrations
{
    [DbContext(typeof(EventAppDbContext))]
    [Migration("20260628230000_AddPasswordResetFields")]
    partial class AddPasswordResetFields
    {
    }
}
