// <auto-generated />
using EventApp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EventApp.Persistence.Migrations
{
    [DbContext(typeof(EventAppDbContext))]
    [Migration("20260703123000_SeedJuly12Activities")]
    partial class SeedJuly12Activities
    {
    }
}
