// <auto-generated />
using EventApp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EventApp.Persistence.Migrations
{
    [DbContext(typeof(EventAppDbContext))]
    [Migration("20260703120000_SeedJuly10Activities")]
    partial class SeedJuly10Activities
    {
    }
}
