// <auto-generated />
using EventApp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EventApp.Persistence.Migrations
{
    [DbContext(typeof(EventAppDbContext))]
    [Migration("20260703121000_RemoveDashActivityDetails")]
    partial class RemoveDashActivityDetails
    {
    }
}
